--- 
abstract: Imager.pm helpers for HTML::FormFu file uploads
author: Carl Franks
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-FormFu-Imager
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::FormFu: 0
  Imager: 0
version: 0.01001
